#!/bin/sh

# 1. On se déplace à la racine du projet pour être sûr du chemin
cd "$(git rev-parse --show-toplevel)"

echo "Executing deploy.sh after commit..."

# 2. On lance le script qui se trouve à la racine
if [ -f "./deploy.sh" ]; then
    sh ./deploy.sh
else
    echo "Erreur : deploy.sh est introuvable à la racine du projet."
fi